---
abstract: 'Compile a log format string to perl-code'
author:
  - 'Masahiro Nagano E<lt>kazeburo@gmail.comE<gt>'
build_requires:
  HTTP::Request::Common: 0
  Test::More: 0.98
  Test::Requires: 0
  Try::Tiny: 0.12
  URI::Escape: 1.60
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-LogFormat-Compiler
no_index:
  directory:
    - inc
provides:
  Apache::LogFormat::Compiler:
    file: lib/Apache/LogFormat/Compiler.pm
    version: 0.10
requires:
  POSIX: 0
  Time::Local: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
