---
abstract: 'Compile LogFormat to perl-code'
author:
  - 'Masahiro Nagano E<lt>kazeburo@gmail.comE<gt>'
build_requires:
  HTTP::Message::PSGI: 0
  HTTP::Request::Common: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-LogFormat-Compiler
no_index:
  directory:
    - inc
provides:
  Apache::LogFormat::Compiler:
    file: lib/Apache/LogFormat/Compiler.pm
    version: 0.03
requires:
  POSIX: 0
  Plack: 1.0013
  Time::Local: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
